// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
#pragma once
import "RealtimeStreaming.idl";
import "Module.idl";

namespace RealtimeStreaming.Plugin
{
    [version(1.0), exclusiveto(ModuleManager), uuid(ed7ca192-2e9d-11e9-b210-d663bd873d93)]
    interface IModuleManager : IInspectable
    {
        UInt32 AddModule(Module pluginModule);

        Module GetModule(UInt32 moduleHandle);

        void ReleaseModule(UInt32 moduleHandle);
    };

    [version(1.0)]
    [marshaling_behavior(agile)]
    [threading(both)]
    runtimeclass ModuleManager
    {
        [default] interface IModuleManager;
    };
}