// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180227.3

#pragma once
#include "winrt/impl/Windows.Perception.Spatial.1.h"
#include "winrt/impl/CameraCapture.Plugin.1.h"

WINRT_EXPORT namespace winrt::CameraCapture::Plugin {

}

namespace winrt::impl {

}

WINRT_EXPORT namespace winrt::CameraCapture::Plugin {

struct WINRT_EBO CaptureEngine :
    CameraCapture::Plugin::ICaptureEngine,
    impl::base<CaptureEngine, CameraCapture::Plugin::Module>,
    impl::require<CaptureEngine, CameraCapture::Plugin::IModule>
{
    CaptureEngine(std::nullptr_t) noexcept {}
    CaptureEngine();
};

struct WINRT_EBO Module :
    CameraCapture::Plugin::IModule
{
    Module(std::nullptr_t) noexcept {}
};

}
