//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetCreator {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VR-PC,HoloLens")]
        public string MaxTargetPlatforms {
            get {
                return ((string)(this["MaxTargetPlatforms"]));
            }
            set {
                this["MaxTargetPlatforms"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000000,100000")]
        public string MaxTargetVertexCount {
            get {
                return ((string)(this["MaxTargetVertexCount"]));
            }
            set {
                this["MaxTargetVertexCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Bundler\\Assets\\HoloAssetCreator.ms")]
        public string MaxScriptLocation {
            get {
                return ((string)(this["MaxScriptLocation"]));
            }
            set {
                this["MaxScriptLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Autodesk\\3ds Max 2017\\")]
        public string MaxInstallLocation {
            get {
                return ((string)(this["MaxInstallLocation"]));
            }
            set {
                this["MaxInstallLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\bundler\\data")]
        public string BaseDataPath {
            get {
                return ((string)(this["BaseDataPath"]));
            }
            set {
                this["BaseDataPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public string MaxDontDecimateLessThan {
            get {
                return ((string)(this["MaxDontDecimateLessThan"]));
            }
            set {
                this["MaxDontDecimateLessThan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CreateUnityAssetBundles {
            get {
                return ((bool)(this["CreateUnityAssetBundles"]));
            }
            set {
                this["CreateUnityAssetBundles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\bundler\\temp")]
        public string TempPath {
            get {
                return ((string)(this["TempPath"]));
            }
            set {
                this["TempPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MaxCombinePartsWithSameMaterial {
            get {
                return ((bool)(this["MaxCombinePartsWithSameMaterial"]));
            }
            set {
                this["MaxCombinePartsWithSameMaterial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MaxQualitySurfAreaCalc {
            get {
                return ((bool)(this["MaxQualitySurfAreaCalc"]));
            }
            set {
                this["MaxQualitySurfAreaCalc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MaxImportAllFiles {
            get {
                return ((bool)(this["MaxImportAllFiles"]));
            }
            set {
                this["MaxImportAllFiles"] = value;
            }
        }
    }
}
