//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetCreator {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class UnitySettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static UnitySettings defaultInstance = ((UnitySettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UnitySettings())));
        
        public static UnitySettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Unity\\Editor\\")]
        public string UnityInstallLocation {
            get {
                return ((string)(this["UnityInstallLocation"]));
            }
            set {
                this["UnityInstallLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Bundler\\Projects\\Unity\\")]
        public string UnityBundleProject {
            get {
                return ((string)(this["UnityBundleProject"]));
            }
            set {
                this["UnityBundleProject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Bundler\\Projects\\Unity\\Assets\\toBundle\\")]
        public string UnityBundleProjectCopy {
            get {
                return ((string)(this["UnityBundleProjectCopy"]));
            }
            set {
                this["UnityBundleProjectCopy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Bundler\\Projects\\Unity_5_6\\")]
        public string UnityBundleProject_5_6 {
            get {
                return ((string)(this["UnityBundleProject_5_6"]));
            }
            set {
                this["UnityBundleProject_5_6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Bundler\\Projects\\Unity_5_6\\Assets\\toBundle\\")]
        public string UnityBundleProjectCopy_5_6 {
            get {
                return ((string)(this["UnityBundleProjectCopy_5_6"]));
            }
            set {
                this["UnityBundleProjectCopy_5_6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Unity_5_6_0f1\\Editor\\")]
        public string UnityInstallLocation_5_6 {
            get {
                return ((string)(this["UnityInstallLocation_5_6"]));
            }
            set {
                this["UnityInstallLocation_5_6"] = value;
            }
        }
    }
}
