// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180227.3

#pragma once
#include "winrt/base.h"

WINRT_WARNING_PUSH

static_assert(winrt::check_version(CPPWINRT_VERSION, "1.0.180227.3"), "Mismatched component and base headers.");
#include "winrt/Windows.Foundation.h"
#include "winrt/Windows.Foundation.Collections.h"
#include "winrt/impl/RealtimeStreaming.2.h"

namespace winrt::impl {

template <typename D> int32_t consume_RealtimeStreaming_IClass<D>::MyProperty() const
{
    int32_t result{};
    check_hresult(WINRT_SHIM(RealtimeStreaming::IClass)->get_MyProperty(&result));
    return result;
}

template <typename D> void consume_RealtimeStreaming_IClass<D>::MyProperty(int32_t value) const
{
    check_hresult(WINRT_SHIM(RealtimeStreaming::IClass)->put_MyProperty(value));
}

template <typename D>
struct produce<D, RealtimeStreaming::IClass> : produce_base<D, RealtimeStreaming::IClass>
{
    HRESULT __stdcall get_MyProperty(int32_t* result) noexcept final
    {
        try
        {
            typename D::abi_guard guard(this->shim());
            *result = detach_from<int32_t>(this->shim().MyProperty());
            return S_OK;
        }
        catch (...)
        {
            return to_hresult();
        }
    }

    HRESULT __stdcall put_MyProperty(int32_t value) noexcept final
    {
        try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().MyProperty(value);
            return S_OK;
        }
        catch (...)
        {
            return to_hresult();
        }
    }
};

}

WINRT_EXPORT namespace winrt::RealtimeStreaming {

inline Class::Class() :
    Class(get_activation_factory<Class>().ActivateInstance<Class>())
{}

}

WINRT_EXPORT namespace std {

template<> struct hash<winrt::RealtimeStreaming::IClass> : winrt::impl::hash_base<winrt::RealtimeStreaming::IClass> {};
template<> struct hash<winrt::RealtimeStreaming::Class> : winrt::impl::hash_base<winrt::RealtimeStreaming::Class> {};

}

WINRT_WARNING_POP
