// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180227.3

#pragma once
#include "winrt/base.h"

WINRT_WARNING_PUSH

static_assert(winrt::check_version(CPPWINRT_VERSION, "1.0.180227.3"), "Mismatched component and base headers.");
#include "winrt/Windows.Foundation.h"
#include "winrt/Windows.Foundation.Collections.h"
#include "winrt/impl/RealtimeStreaming.Common.2.h"
#include "winrt/RealtimeStreaming.h"

namespace winrt::impl {

}

WINRT_EXPORT namespace winrt::RealtimeStreaming::Common {

}

WINRT_EXPORT namespace std {


}

WINRT_WARNING_POP
