// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
#pragma once

import "Connection.idl";
import "NetworkMediaSink.idl";

namespace RealtimeStreaming.Media
{
    [version(1.0)]
    enum SinkStreamState
    {
        NotSet = 0,
        Ready,
        Started,
        Stopped,
        Paused,
        Count
    };

    [version(1.0)]
    enum SinkStreamOperation
    {
        SetMediaType = 0,
        Start,
        Restart,
        Pause,
        Stop,
        ProcessSample,
        PlaceMarker,
        Count   // Number of operations
    };

    /*
    [activatable(1.0)]
    [marshaling_behavior(agile)]
    [threading(both)]
    [version(1.0)]
    */
    runtimeclass NetworkMediaSinkStream : Windows.Media.IMediaExtension
    {
        NetworkMediaSinkStream();
        NetworkMediaSinkStream(UInt32 streamId,
                RealtimeStreaming.Network.Connection dataConnection,
                RealtimeStreaming.Media.NetworkMediaSink parentMediaSink);

        HRESULT Start(Int64 start); //MFTIME
        HRESULT Restart();
        HRESULT Stop();
        HRESULT Pause();
        HRESULT Shutdown();
    };
}