// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180227.3

#pragma once
#include "winrt/Windows.Foundation.Collections.h"
#include "winrt/Windows.Media.Capture.h"
#include "winrt/Windows.Media.MediaProperties.h"
#include "winrt/Windows.Media.h"
#include "winrt/Windows.Media.Effects.h"
#include "winrt/CameraCapture.Media.Capture.h"

namespace winrt::CameraCapture::Media::Capture::implementation {

template <typename D, typename... I>
struct WINRT_EBO Payload_base : implements<D, CameraCapture::Media::Capture::IPayload, I...>
{
    using base_type = Payload_base;
    using class_type = CameraCapture::Media::Capture::Payload;
    using implements_type = typename Payload_base::implements_type;
    using implements_type::implements_type;
    
    operator class_type() const noexcept
    {
        static_assert(std::is_same_v<typename impl::implements_default_interface<D>::type, impl::default_interface_t<class_type>>);
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<impl::default_interface_t<class_type>>(*this)));
        return result;
    }

    hstring GetRuntimeClassName() const
    {
        return L"CameraCapture.Media.Capture.Payload";
    }
};

}

#if defined(WINRT_FORCE_INCLUDE_PAYLOAD_XAML_G_H) || __has_include("Media/Capture/Payload.xaml.g.h")

#include "Media/Capture/Payload.xaml.g.h"

#else

namespace winrt::CameraCapture::Media::Capture::implementation
{
    template <typename D, typename... I>
    using PayloadT = Payload_base<D, I...>;
}

#endif
