// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
#pragma once
import "Network/Connection.idl";
import "Plugin/ModuleManager.idl";

namespace RealtimeStreaming.Network
{
    /*
    [version(1.0), exclusiveto(Connector), uuid(6229e89c-2e85-11e9-b210-d663bd873d93)]
    interface IConnector : IInspectable
    {
        Windows.Foundation.IAsyncOperation<Connection> ConnectAsync();

        event Windows.Foundation.EventHandler<Boolean> Closed;
    };*/

    /*
    [version(1.0), exclusiveto(Connector), uuid(6229eb26-2e85-11e9-b210-d663bd873d93)]
    interface IConnectorFactory : IInspectable
    {

    }*/

    /*
    [marshaling_behavior(agile)]
    [threading(both)]
    [version(1.0)]
    */
    [default_interface]
    runtimeclass Connector : RealtimeStreaming.Plugin.Module
    {
        //[default] interface IConnector;
        //Connector(HSTRING hostAddress, UInt16 port);
        Windows.Foundation.IAsyncOperation<Connection> ConnectAsync();

        event Windows.Foundation.EventHandler<Boolean> Closed;
    };
}