// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once
#include "winrt/impl/RealtimeStreaming.Network.1.h"
#include "winrt/impl/Windows.Foundation.Collections.1.h"
#include "winrt/impl/Windows.Media.Core.1.h"
#include "winrt/impl/Windows.Media.MediaProperties.1.h"
#include "winrt/impl/RealtimeStreaming.Plugin.1.h"
#include "winrt/impl/Windows.Media.1.h"
#include "winrt/impl/RealtimeStreaming.Media.1.h"

WINRT_EXPORT namespace winrt::RealtimeStreaming::Media {

}

namespace winrt::impl {

}

WINRT_EXPORT namespace winrt::RealtimeStreaming::Media {

struct WINRT_EBO NetworkMediaSink :
    RealtimeStreaming::Media::INetworkMediaSink,
    impl::require<NetworkMediaSink, Windows::Media::IMediaExtension>
{
    NetworkMediaSink(std::nullptr_t) noexcept {}
    NetworkMediaSink();
    NetworkMediaSink(Windows::Media::MediaProperties::AudioEncodingProperties const& audioEncodingProperties, Windows::Media::MediaProperties::VideoEncodingProperties const& videoEncodingProperties, RealtimeStreaming::Network::Connection const& connection);
};

struct WINRT_EBO NetworkMediaSinkStream :
    RealtimeStreaming::Media::INetworkMediaSinkStream,
    impl::require<NetworkMediaSinkStream, Windows::Media::IMediaExtension>
{
    NetworkMediaSinkStream(std::nullptr_t) noexcept {}
    NetworkMediaSinkStream();
    NetworkMediaSinkStream(uint32_t streamId, RealtimeStreaming::Network::Connection const& dataConnection, RealtimeStreaming::Media::NetworkMediaSink const& parentMediaSink);
};

struct WINRT_EBO RTSchemeHandler :
    RealtimeStreaming::Media::IRTSchemeHandler,
    impl::require<RTSchemeHandler, Windows::Media::IMediaExtension>
{
    RTSchemeHandler(std::nullptr_t) noexcept {}
    RTSchemeHandler();
};

struct WINRT_EBO RealtimeMediaPlayer :
    RealtimeStreaming::Media::IRealtimeMediaPlayer,
    impl::require<RealtimeMediaPlayer, RealtimeStreaming::Plugin::IRTModule>
{
    RealtimeMediaPlayer(std::nullptr_t) noexcept {}
    RealtimeMediaPlayer();
};

struct WINRT_EBO RealtimeMediaSource :
    RealtimeStreaming::Media::IRealtimeMediaSource,
    impl::require<RealtimeMediaSource, Windows::Media::IMediaExtension>
{
    RealtimeMediaSource(std::nullptr_t) noexcept {}
    RealtimeMediaSource();
};

struct WINRT_EBO RealtimeServer :
    RealtimeStreaming::Media::IRealtimeServer,
    impl::require<RealtimeServer, RealtimeStreaming::Plugin::IRTModule>
{
    RealtimeServer(std::nullptr_t) noexcept {}
    RealtimeServer(RealtimeStreaming::Network::Connection const& connection, winrt::guid const& inputMediaType, Windows::Media::MediaProperties::MediaEncodingProfile const& mediaEncodingProperties);
};

}
