// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once
#include "winrt/impl/RealtimeStreaming.Plugin.0.h"

WINRT_EXPORT namespace winrt::RealtimeStreaming::Plugin {

struct WINRT_EBO IPluginManager :
    Windows::Foundation::IInspectable,
    impl::consume_t<IPluginManager>
{
    IPluginManager(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRTModule :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRTModule>
{
    IRTModule(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRTModuleManager :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRTModuleManager>
{
    IRTModuleManager(std::nullptr_t = nullptr) noexcept {}
};

}
