// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180227.3

#pragma once
#include "winrt/impl/RealtimeStreaming.1.h"

WINRT_EXPORT namespace winrt::RealtimeStreaming {

}

namespace winrt::impl {

}

WINRT_EXPORT namespace winrt::RealtimeStreaming {

struct WINRT_EBO Class :
    RealtimeStreaming::IClass
{
    Class(std::nullptr_t) noexcept {}
    Class();
};

}
