// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once
#include "winrt/impl/RealtimeStreaming.Plugin.0.h"

WINRT_EXPORT namespace winrt::RealtimeStreaming::Plugin {

struct WINRT_EBO IModule :
    Windows::Foundation::IInspectable,
    impl::consume_t<IModule>
{
    IModule(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IModuleFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IModuleFactory>
{
    IModuleFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IModuleManager :
    Windows::Foundation::IInspectable,
    impl::consume_t<IModuleManager>
{
    IModuleManager(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IPluginManager :
    Windows::Foundation::IInspectable,
    impl::consume_t<IPluginManager>
{
    IPluginManager(std::nullptr_t = nullptr) noexcept {}
};

}
