// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180227.3

#pragma once
#include "winrt/impl/RealtimeStreaming.Network.0.h"
#include "winrt/impl/Windows.Foundation.Collections.0.h"
#include "winrt/impl/Windows.Media.Core.0.h"
#include "winrt/impl/Windows.Media.MediaProperties.0.h"
#include "winrt/impl/RealtimeStreaming.Plugin.0.h"
#include "winrt/impl/Windows.Media.0.h"
#include "winrt/impl/RealtimeStreaming.Media.0.h"

WINRT_EXPORT namespace winrt::RealtimeStreaming::Media {

struct WINRT_EBO INetworkMediaSink :
    Windows::Foundation::IInspectable,
    impl::consume_t<INetworkMediaSink>
{
    INetworkMediaSink(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO INetworkMediaSinkStream :
    Windows::Foundation::IInspectable,
    impl::consume_t<INetworkMediaSinkStream>
{
    INetworkMediaSinkStream(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRTSchemeHandler :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRTSchemeHandler>
{
    IRTSchemeHandler(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRealtimeMediaPlayer :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRealtimeMediaPlayer>
{
    IRealtimeMediaPlayer(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRealtimeMediaSource :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRealtimeMediaSource>
{
    IRealtimeMediaSource(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRealtimeServer :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRealtimeServer>
{
    IRealtimeServer(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRealtimeServerFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRealtimeServerFactory>
{
    IRealtimeServerFactory(std::nullptr_t = nullptr) noexcept {}
};

}
