// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once
#include "winrt/impl/RealtimeStreaming.Plugin.1.h"

WINRT_EXPORT namespace winrt::RealtimeStreaming::Plugin {

}

namespace winrt::impl {

}

WINRT_EXPORT namespace winrt::RealtimeStreaming::Plugin {

struct WINRT_EBO ModuleManager :
    RealtimeStreaming::Plugin::IModuleManager
{
    ModuleManager(std::nullptr_t) noexcept {}
    ModuleManager();
};

struct WINRT_EBO PluginManager :
    RealtimeStreaming::Plugin::IPluginManager
{
    PluginManager(std::nullptr_t) noexcept {}
    PluginManager();
};

}
