// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180227.3

#pragma once
#include "winrt/impl/RealtimeStreaming.0.h"

WINRT_EXPORT namespace winrt::RealtimeStreaming {

struct WINRT_EBO IClass :
    Windows::Foundation::IInspectable,
    impl::consume_t<IClass>
{
    IClass(std::nullptr_t = nullptr) noexcept {}
};

}
