// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once
#include "winrt/impl/RealtimeStreaming.Common.0.h"

WINRT_EXPORT namespace winrt::RealtimeStreaming::Common {

}
