// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180227.3

#pragma once
#include "winrt/Windows.Perception.Spatial.h"
#include "winrt/CameraCapture.Plugin.h"

namespace winrt::CameraCapture::Plugin::implementation {

template <typename D, typename B, typename... I>
struct WINRT_EBO CaptureEngine_base : implements<D, CameraCapture::Plugin::ICaptureEngine, B, no_module_lock, I...>
{
    using base_type = CaptureEngine_base;
    using class_type = CameraCapture::Plugin::CaptureEngine;
    using implements_type = typename CaptureEngine_base::implements_type;
    using implements_type::implements_type;
    
    operator class_type() const noexcept
    {
        static_assert(std::is_same_v<typename impl::implements_default_interface<D>::type, impl::default_interface_t<class_type>>);
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<impl::default_interface_t<class_type>>(*this)));
        return result;
    }

    hstring GetRuntimeClassName() const
    {
        return L"CameraCapture.Plugin.CaptureEngine";
    }
};

}

namespace winrt::CameraCapture::Plugin::factory_implementation {

template <typename D, typename T, typename... I>
struct WINRT_EBO CaptureEngineT : implements<D, Windows::Foundation::IActivationFactory, I...>
{
    hstring GetRuntimeClassName() const
    {
        return L"CameraCapture.Plugin.CaptureEngine";
    }

    Windows::Foundation::IInspectable ActivateInstance() const
    {
        return make<T>();
    }
};

}

#if defined(WINRT_FORCE_INCLUDE_CAPTUREENGINE_XAML_G_H) || __has_include("Plugin/CaptureEngine.xaml.g.h")

#include "Plugin/CaptureEngine.xaml.g.h"

#else

namespace winrt::CameraCapture::Plugin::implementation
{
    template <typename D, typename... I>
    using CaptureEngineT = CaptureEngine_base<D, I...>;
}

#endif
