// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180227.3

#pragma once
#include "winrt/impl/Windows.Perception.Spatial.0.h"
#include "winrt/impl/CameraCapture.Plugin.0.h"

WINRT_EXPORT namespace winrt::CameraCapture::Plugin {

struct WINRT_EBO ICaptureEngine :
    Windows::Foundation::IInspectable,
    impl::consume_t<ICaptureEngine>
{
    ICaptureEngine(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IModule :
    Windows::Foundation::IInspectable,
    impl::consume_t<IModule>
{
    IModule(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IModuleFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IModuleFactory>
{
    IModuleFactory(std::nullptr_t = nullptr) noexcept {}
};

}
