// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180227.3

#pragma once
#include "winrt/impl/Windows.Foundation.Collections.1.h"
#include "winrt/impl/Windows.Media.Capture.1.h"
#include "winrt/impl/Windows.Media.MediaProperties.1.h"
#include "winrt/impl/Windows.Media.1.h"
#include "winrt/impl/Windows.Media.Effects.1.h"
#include "winrt/impl/CameraCapture.Media.Capture.1.h"

WINRT_EXPORT namespace winrt::CameraCapture::Media::Capture {

}

namespace winrt::impl {

}

WINRT_EXPORT namespace winrt::CameraCapture::Media::Capture {

struct WINRT_EBO AudioPayload :
    CameraCapture::Media::Capture::IAudioPayload,
    impl::base<AudioPayload, CameraCapture::Media::Capture::Payload>,
    impl::require<AudioPayload, CameraCapture::Media::Capture::IPayload>
{
    AudioPayload(std::nullptr_t) noexcept {}
    AudioPayload();
};

struct WINRT_EBO MrcAudioEffect :
    CameraCapture::Media::Capture::IMrcAudioEffect,
    impl::require<MrcAudioEffect, Windows::Media::Effects::IAudioEffectDefinition>
{
    MrcAudioEffect(std::nullptr_t) noexcept {}
    MrcAudioEffect();
};

struct WINRT_EBO MrcVideoEffect :
    CameraCapture::Media::Capture::IMrcVideoEffect,
    impl::require<MrcVideoEffect, Windows::Media::Effects::IVideoEffectDefinition>
{
    MrcVideoEffect(std::nullptr_t) noexcept {}
    MrcVideoEffect();
};

struct WINRT_EBO Payload :
    CameraCapture::Media::Capture::IPayload
{
    Payload(std::nullptr_t) noexcept {}
};

struct WINRT_EBO PayloadHandler :
    CameraCapture::Media::Capture::IPayloadHandler
{
    PayloadHandler(std::nullptr_t) noexcept {}
    PayloadHandler();
};

struct WINRT_EBO Sink :
    CameraCapture::Media::Capture::ISink,
    impl::require<Sink, Windows::Media::IMediaExtension>
{
    Sink(std::nullptr_t) noexcept {}
    Sink(Windows::Media::MediaProperties::MediaEncodingProfile const& encodingProfile);
};

struct WINRT_EBO StreamSink :
    CameraCapture::Media::Capture::IStreamSink,
    impl::require<StreamSink, Windows::Media::IMediaExtension>
{
    StreamSink(std::nullptr_t) noexcept {}
    StreamSink(uint8_t index, Windows::Media::MediaProperties::IMediaEncodingProperties const& encodingProperties, CameraCapture::Media::Capture::Sink const& parent);
};

struct WINRT_EBO VideoPayload :
    CameraCapture::Media::Capture::IVideoPayload,
    impl::base<VideoPayload, CameraCapture::Media::Capture::Payload>,
    impl::require<VideoPayload, CameraCapture::Media::Capture::IPayload>
{
    VideoPayload(std::nullptr_t) noexcept {}
    VideoPayload();
};

}
