// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
#pragma once

import "Plugin/ModuleManager.idl";

namespace RealtimeStreaming.Media
{
    [version(1.0)]
    [marshaling_behavior(agile)]
    [threading(both)]
    runtimeclass RealtimeMediaPlayer : RealtimeStreaming.Plugin.Module
    {
        RealtimeMediaPlayer();

        event Windows.Foundation.EventHandler<RealtimeMediaPlayer> Closed;
    };
}
