// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180227.3

#pragma once
#include "winrt/Windows.Foundation.Collections.h"
#include "winrt/Windows.Media.Capture.h"
#include "winrt/Windows.Media.MediaProperties.h"
#include "winrt/Windows.Media.h"
#include "winrt/Windows.Media.Effects.h"
#include "winrt/CameraCapture.Media.Capture.h"

namespace winrt::CameraCapture::Media::Capture::implementation {

template <typename D, typename... I>
struct WINRT_EBO MrcVideoEffect_base : implements<D, CameraCapture::Media::Capture::IMrcVideoEffect, Windows::Media::Effects::IVideoEffectDefinition, I...>
{
    using base_type = MrcVideoEffect_base;
    using class_type = CameraCapture::Media::Capture::MrcVideoEffect;
    using implements_type = typename MrcVideoEffect_base::implements_type;
    using implements_type::implements_type;
    
    operator class_type() const noexcept
    {
        static_assert(std::is_same_v<typename impl::implements_default_interface<D>::type, impl::default_interface_t<class_type>>);
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<impl::default_interface_t<class_type>>(*this)));
        return result;
    }

    hstring GetRuntimeClassName() const
    {
        return L"CameraCapture.Media.Capture.MrcVideoEffect";
    }
};

}

namespace winrt::CameraCapture::Media::Capture::factory_implementation {

template <typename D, typename T, typename... I>
struct WINRT_EBO MrcVideoEffectT : implements<D, Windows::Foundation::IActivationFactory, I...>
{
    hstring GetRuntimeClassName() const
    {
        return L"CameraCapture.Media.Capture.MrcVideoEffect";
    }

    Windows::Foundation::IInspectable ActivateInstance() const
    {
        return make<T>();
    }
};

}

#if defined(WINRT_FORCE_INCLUDE_MRCVIDEOEFFECT_XAML_G_H) || __has_include("Media/Capture/MrcVideoEffect.xaml.g.h")

#include "Media/Capture/MrcVideoEffect.xaml.g.h"

#else

namespace winrt::CameraCapture::Media::Capture::implementation
{
    template <typename D, typename... I>
    using MrcVideoEffectT = MrcVideoEffect_base<D, I...>;
}

#endif
