// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180227.3

#pragma once
#include "winrt/RealtimeStreaming.h"

namespace winrt::RealtimeStreaming::implementation {

template <typename D, typename... I>
struct WINRT_EBO Class_base : implements<D, RealtimeStreaming::IClass, I...>
{
    using base_type = Class_base;
    using class_type = RealtimeStreaming::Class;
    using implements_type = typename Class_base::implements_type;
    using implements_type::implements_type;
    
    operator class_type() const noexcept
    {
        static_assert(std::is_same_v<typename impl::implements_default_interface<D>::type, impl::default_interface_t<class_type>>);
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<impl::default_interface_t<class_type>>(*this)));
        return result;
    }

    hstring GetRuntimeClassName() const
    {
        return L"RealtimeStreaming.Class";
    }
};

}

namespace winrt::RealtimeStreaming::factory_implementation {

template <typename D, typename T, typename... I>
struct WINRT_EBO ClassT : implements<D, Windows::Foundation::IActivationFactory, I...>
{
    hstring GetRuntimeClassName() const
    {
        return L"RealtimeStreaming.Class";
    }

    Windows::Foundation::IInspectable ActivateInstance() const
    {
        return make<T>();
    }
};

}

#if defined(WINRT_FORCE_INCLUDE_CLASS_XAML_G_H) || __has_include("Class.xaml.g.h")

#include "Class.xaml.g.h"

#else

namespace winrt::RealtimeStreaming::implementation
{
    template <typename D, typename... I>
    using ClassT = Class_base<D, I...>;
}

#endif
