// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once

#include "winrt/RealtimeStreaming.Common.h"
#include "winrt/Windows.Networking.Sockets.h"
#include "winrt/RealtimeStreaming.Plugin.h"
#include "winrt/Windows.Storage.Streams.h"
#include "winrt/RealtimeStreaming.Network.h"

namespace winrt::RealtimeStreaming::Network::implementation {

template <typename D, typename B, typename... I>
struct WINRT_EBO Connector_base : implements<D, RealtimeStreaming::Network::IConnector, B, no_module_lock, I...>
{
    using base_type = Connector_base;
    using class_type = RealtimeStreaming::Network::Connector;
    using implements_type = typename Connector_base::implements_type;
    using implements_type::implements_type;
    
#if _MSC_VER < 1914
    operator class_type() const noexcept
    {
        static_assert(std::is_same_v<typename impl::implements_default_interface<D>::type, default_interface<class_type>>);
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<default_interface<class_type>>(*this)));
        return result;
    }
#else
    operator impl::producer_ref<class_type> const() const noexcept
    {
        return { to_abi<default_interface<class_type>>(this) };
    }
#endif

    hstring GetRuntimeClassName() const
    {
        return L"RealtimeStreaming.Network.Connector";
    }
};

}

#if defined(WINRT_FORCE_INCLUDE_CONNECTOR_XAML_G_H) || __has_include("Network.Connector.xaml.g.h")

#include "Network.Connector.xaml.g.h"

#else

namespace winrt::RealtimeStreaming::Network::implementation
{
    template <typename D, typename... I>
    using ConnectorT = Connector_base<D, I...>;
}

#endif
