// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once

#include "winrt/RealtimeStreaming.Plugin.h"

namespace winrt::RealtimeStreaming::Plugin::implementation {

template <typename D, typename... I>
struct WINRT_EBO PluginManager_base : implements<D, RealtimeStreaming::Plugin::IPluginManager, I...>
{
    using base_type = PluginManager_base;
    using class_type = RealtimeStreaming::Plugin::PluginManager;
    using implements_type = typename PluginManager_base::implements_type;
    using implements_type::implements_type;
    
#if _MSC_VER < 1914
    operator class_type() const noexcept
    {
        static_assert(std::is_same_v<typename impl::implements_default_interface<D>::type, default_interface<class_type>>);
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<default_interface<class_type>>(*this)));
        return result;
    }
#else
    operator impl::producer_ref<class_type> const() const noexcept
    {
        return { to_abi<default_interface<class_type>>(this) };
    }
#endif

    hstring GetRuntimeClassName() const
    {
        return L"RealtimeStreaming.Plugin.PluginManager";
    }
};

}

namespace winrt::RealtimeStreaming::Plugin::factory_implementation {

template <typename D, typename T, typename... I>
struct WINRT_EBO PluginManagerT : implements<D, Windows::Foundation::IActivationFactory, I...>
{
    using instance_type = RealtimeStreaming::Plugin::PluginManager;

    hstring GetRuntimeClassName() const
    {
        return L"RealtimeStreaming.Plugin.PluginManager";
    }

    Windows::Foundation::IInspectable ActivateInstance() const
    {
        return make<T>();
    }
};

}

#if defined(WINRT_FORCE_INCLUDE_PLUGINMANAGER_XAML_G_H) || __has_include("Plugin.PluginManager.xaml.g.h")

#include "Plugin.PluginManager.xaml.g.h"

#else

namespace winrt::RealtimeStreaming::Plugin::implementation
{
    template <typename D, typename... I>
    using PluginManagerT = PluginManager_base<D, I...>;
}

#endif
