// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once

#include "winrt/RealtimeStreaming.Plugin.h"

namespace winrt::RealtimeStreaming::Plugin::implementation {

template <typename D, typename... I>
struct WINRT_EBO ModuleManager_base : implements<D, RealtimeStreaming::Plugin::IModuleManager, I...>
{
    using base_type = ModuleManager_base;
    using class_type = RealtimeStreaming::Plugin::ModuleManager;
    using implements_type = typename ModuleManager_base::implements_type;
    using implements_type::implements_type;
    
#if _MSC_VER < 1914
    operator class_type() const noexcept
    {
        static_assert(std::is_same_v<typename impl::implements_default_interface<D>::type, default_interface<class_type>>);
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<default_interface<class_type>>(*this)));
        return result;
    }
#else
    operator impl::producer_ref<class_type> const() const noexcept
    {
        return { to_abi<default_interface<class_type>>(this) };
    }
#endif

    hstring GetRuntimeClassName() const
    {
        return L"RealtimeStreaming.Plugin.ModuleManager";
    }
};

}

#if defined(WINRT_FORCE_INCLUDE_MODULEMANAGER_XAML_G_H) || __has_include("Plugin.ModuleManager.xaml.g.h")

#include "Plugin.ModuleManager.xaml.g.h"

#else

namespace winrt::RealtimeStreaming::Plugin::implementation
{
    template <typename D, typename... I>
    using ModuleManagerT = ModuleManager_base<D, I...>;
}

#endif
