// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

import "oaidl.idl";
import "ocidl.idl";

import "Connection.idl";
import "ModuleManager.idl";

namespace RealtimeStreaming.Network
{

    [activatable(1.0)]
    [marshaling_behavior(agile)]
    [threading(both)]
    [version(1.0)]
    runtimeclass Connector : RealtimeStreaming.Plugin.Module
    {
        Connector(hstring hostAddress, UINT16 port);

        IAsyncAction<Connection> ConnectAsync();

        event Windows.Foundation.EventHandler Closed;
    };
}