// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
#pragma once
import "Connection.idl";
import "ModuleManager.idl";

namespace RealtimeStreaming.Network
{
    [default_interface]
    runtimeclass Connector : RealtimeStreaming.Plugin.IRTModule
    {
        Windows.Foundation.IAsyncOperation<Connection> ConnectAsync(Windows.Networking.HostName hostAddress, UInt16 port);
        
        Windows.Foundation.IAsyncOperation<Connection> DiscoverAsync();

        event Windows.Foundation.EventHandler<Boolean> Closed;
    };
}