// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

import "oaidl.idl";
import "ocidl.idl";

import "Connection.idl";
import "ModuleManager.idl";

namespace RealtimeStreaming.Network
{
    [version(1.0), exclusiveto(Connector), uuid(6229e89c-2e85-11e9-b210-d663bd873d93)]
    interface IConnector : IInspectable
    {
        Windows.Foundation.IAsyncOperation<Connection> ConnectAsync();

        event Windows.Foundation.EventHandler<Boolean> Closed;
    };

    /*
    [version(1.0), exclusiveto(Connector), uuid(6229eb26-2e85-11e9-b210-d663bd873d93)]
    interface IConnectorFactory : IInspectable
    {

    }*/

    [activatable(1.0)]
    [marshaling_behavior(agile)]
    [threading(both)]
    [version(1.0)]
    runtimeclass Connector : RealtimeStreaming.Plugin.Module
    {
        [default] interface IConnector;
        //Connector(HSTRING hostAddress, UInt16 port);
    };
}