// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

import "oaidl.idl";
import "ocidl.idl";

import "Windows.Foundation.idl";
import "Windows.Networking.Sockets.idl";

import "RealtimeStreaming.idl";
import "DataBundle.idl";
//import "DataBundleArgs.idl";
import "ModuleManager.idl";

namespace RealtimeStreaming.Network
{
    [activatable(1.0)]
    [marshaling_behavior(agile)]
    [threading(both)]
    [version(1.0)]
    runtimeclass Connection : RealtimeStreaming.Plugin.Module
    {
        Connection();
        //Connection(Windows.Networking.Sockets.StreamSocket streamSocket);

        HRESULT SendPayloadType(RealtimeStreaming.PayloadType type);
        HRESULT SendBundle(IDataBundle dataBundle);
        Windows.Foundation.IAsyncAction SendBundleAsync(IDataBundle dataBundle);

        boolean IsConnected{ get; };

        event Windows.Foundation.EventHandler<IInspectable> Disconnected;
        //event Windows.Foundation.EventHandler<BundleReceivedArgs> Received;
    };
}