// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180227.3

#pragma once
#include "winrt/RealtimeStreaming.Plugin.h"

namespace winrt::RealtimeStreaming::Plugin::implementation {

template <typename D, typename... I>
struct WINRT_EBO ModuleManager_base : implements<D, RealtimeStreaming::Plugin::IModuleManager, I...>
{
    using base_type = ModuleManager_base;
    using class_type = RealtimeStreaming::Plugin::ModuleManager;
    using implements_type = typename ModuleManager_base::implements_type;
    using implements_type::implements_type;
    
    operator class_type() const noexcept
    {
        static_assert(std::is_same_v<typename impl::implements_default_interface<D>::type, impl::default_interface_t<class_type>>);
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<impl::default_interface_t<class_type>>(*this)));
        return result;
    }

    hstring GetRuntimeClassName() const
    {
        return L"RealtimeStreaming.Plugin.ModuleManager";
    }
};

}

#if defined(WINRT_FORCE_INCLUDE_MODULEMANAGER_XAML_G_H) || __has_include("Plugin/ModuleManager.xaml.g.h")

#include "Plugin/ModuleManager.xaml.g.h"

#else

namespace winrt::RealtimeStreaming::Plugin::implementation
{
    template <typename D, typename... I>
    using ModuleManagerT = ModuleManager_base<D, I...>;
}

#endif
