// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180227.3

#include "pch.h"
#ifndef WINRT_SUPPRESS_MODULE_EXPORTS

#include "Media.Capture.AudioPayload.h"
#include "Media.Capture.MrcAudioEffect.h"
#include "Media.Capture.MrcVideoEffect.h"
#include "Media.Capture.PayloadHandler.h"
#include "Media.Capture.Sink.h"
#include "Media.Capture.StreamSink.h"
#include "Media.Capture.VideoPayload.h"
#include "Plugin.CaptureEngine.h"


HRESULT __stdcall WINRT_CanUnloadNow()
{
#ifdef _WRL_MODULE_H_
    if (!::Microsoft::WRL::Module<::Microsoft::WRL::InProc>::GetModule().Terminate())
    {
        return S_FALSE;
    }
#endif

    if (winrt::get_module_lock())
    {
        return S_FALSE;
    }

    winrt::clear_factory_cache();
    return S_OK;
}

HRESULT __stdcall WINRT_GetActivationFactory(HSTRING classId, void** factory)
{
    try
    {
        *factory = nullptr;
        wchar_t const* const name = WindowsGetStringRawBuffer(classId, nullptr);

        if (0 == wcscmp(name, L"CameraCapture.Media.Capture.AudioPayload"))
        {
            *factory = winrt::detach_abi(winrt::make<winrt::CameraCapture::Media::Capture::factory_implementation::AudioPayload>());
            return S_OK;
        }

        if (0 == wcscmp(name, L"CameraCapture.Media.Capture.MrcAudioEffect"))
        {
            *factory = winrt::detach_abi(winrt::make<winrt::CameraCapture::Media::Capture::factory_implementation::MrcAudioEffect>());
            return S_OK;
        }

        if (0 == wcscmp(name, L"CameraCapture.Media.Capture.MrcVideoEffect"))
        {
            *factory = winrt::detach_abi(winrt::make<winrt::CameraCapture::Media::Capture::factory_implementation::MrcVideoEffect>());
            return S_OK;
        }

        if (0 == wcscmp(name, L"CameraCapture.Media.Capture.PayloadHandler"))
        {
            *factory = winrt::detach_abi(winrt::make<winrt::CameraCapture::Media::Capture::factory_implementation::PayloadHandler>());
            return S_OK;
        }

        if (0 == wcscmp(name, L"CameraCapture.Media.Capture.Sink"))
        {
            *factory = winrt::detach_abi(winrt::make<winrt::CameraCapture::Media::Capture::factory_implementation::Sink>());
            return S_OK;
        }

        if (0 == wcscmp(name, L"CameraCapture.Media.Capture.StreamSink"))
        {
            *factory = winrt::detach_abi(winrt::make<winrt::CameraCapture::Media::Capture::factory_implementation::StreamSink>());
            return S_OK;
        }

        if (0 == wcscmp(name, L"CameraCapture.Media.Capture.VideoPayload"))
        {
            *factory = winrt::detach_abi(winrt::make<winrt::CameraCapture::Media::Capture::factory_implementation::VideoPayload>());
            return S_OK;
        }

        if (0 == wcscmp(name, L"CameraCapture.Plugin.CaptureEngine"))
        {
            *factory = winrt::detach_abi(winrt::make<winrt::CameraCapture::Plugin::factory_implementation::CaptureEngine>());
            return S_OK;
        }

#ifdef _WRL_MODULE_H_
        return ::Microsoft::WRL::Module<::Microsoft::WRL::InProc>::GetModule().GetActivationFactory(classId, reinterpret_cast<::IActivationFactory**>(factory));
#else
        return winrt::hresult_class_not_available().to_abi();
#endif
    }
    catch (...)
    {
        return winrt::to_hresult();
    }
}

#endif
