// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180227.3

#pragma once
#include "winrt/RealtimeStreaming.Network.h"
#include "winrt/Windows.Foundation.Collections.h"
#include "winrt/Windows.Media.Core.h"
#include "winrt/Windows.Media.MediaProperties.h"
#include "winrt/RealtimeStreaming.Plugin.h"
#include "winrt/Windows.Media.h"
#include "winrt/RealtimeStreaming.Media.h"

namespace winrt::RealtimeStreaming::Media::implementation {

template <typename D, typename... I>
struct WINRT_EBO NetworkMediaSinkStream_base : implements<D, RealtimeStreaming::Media::INetworkMediaSinkStream, Windows::Media::IMediaExtension, I...>
{
    using base_type = NetworkMediaSinkStream_base;
    using class_type = RealtimeStreaming::Media::NetworkMediaSinkStream;
    using implements_type = typename NetworkMediaSinkStream_base::implements_type;
    using implements_type::implements_type;
    
    operator class_type() const noexcept
    {
        static_assert(std::is_same_v<typename impl::implements_default_interface<D>::type, impl::default_interface_t<class_type>>);
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<impl::default_interface_t<class_type>>(*this)));
        return result;
    }

    hstring GetRuntimeClassName() const
    {
        return L"RealtimeStreaming.Media.NetworkMediaSinkStream";
    }
};

}

#if defined(WINRT_FORCE_INCLUDE_NETWORKMEDIASINKSTREAM_XAML_G_H) || __has_include("Media/NetworkMediaSinkStream.xaml.g.h")

#include "Media/NetworkMediaSinkStream.xaml.g.h"

#else

namespace winrt::RealtimeStreaming::Media::implementation
{
    template <typename D, typename... I>
    using NetworkMediaSinkStreamT = NetworkMediaSinkStream_base<D, I...>;
}

#endif
